### PR TITLE
Convert to Node.js

### PR DESCRIPTION
**Pull request by supersonictw**
The project will be convert to `TypeScript`, for performance and flexible.

- [x] init typescript project
- [x] LINE trigger
- [x] Matrix trigger
- [x] LINE sender
- [x] Matrix sender

### CODE REVIEW

**Comment by virgil9306** [comment]
Very cool project. Thanks for developing it.

Do you have any plan to have `Dockerfile` or `docker-compose` that can use Environment Variables for config? It may be easy for people to use with this.

**Comment by virgil9306** [comment]
Very cool project. Thanks for developing it.

Using `node` will make it easy to dockerize this project.
So I was wondering if you have any plan to have `Dockerfile` that can use Environment Variables for config?

**Comment by supersonictw** [comment]
Why typescript? Why?

**Comment by supersonictw** [comment]
Refactor with https://github.com/web-tech-tw/template.recv

**Pull request merged**
